"""
HackerBoard — Step 3 Design Architecture Diagram
> Generated by design agent | 2026-02-20

Prerequisites:
  pip install diagrams
  apt-get install -y graphviz

Generate:
  python3 agent-output/hacker-board/03-des-diagram.py
"""

import os

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import ContainerRegistries
from diagrams.azure.database import CosmosDb
from diagrams.azure.identity import ActiveDirectory, EntraManagedIdentities
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces
from diagrams.azure.web import AppServices, AppServicePlans
from diagrams.onprem.client import User, Users
from diagrams.onprem.vcs import Github

OUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "03-des-diagram")

graph_attr = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.9",
    "ranksep": "1.0",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "16",
    "dpi": "150",
}

node_attr = {
    "fontname": "Arial Bold",
    "fontsize": "11",
    "labelloc": "t",
}

cluster_style = {
    "margin": "30",
    "fontname": "Arial Bold",
    "fontsize": "13",
}


def edge_runtime(flow_label: str):
    return Edge(style="bold", color="#2E7D32", label=flow_label)


def edge_control(flow_label: str):
    return Edge(style="dashed", color="#1565C0", label=flow_label)


def edge_observability(flow_label: str):
    return Edge(style="dotted", color="#7B1FA2", label=flow_label)


with Diagram(
    "HackerBoard — Design Architecture\n(centralus · App Service + ACR + Cosmos DB Serverless)",
    filename=OUT_FILE,
    show=False,
    direction="LR",
    graph_attr=graph_attr,
    node_attr=node_attr,
):
    with Cluster("External", graph_attr={**cluster_style, "bgcolor": "#F5F5F5"}) as clu_ext_boundary:
        n_edge_users_participants = Users("Hackathon\nParticipants")
        n_edge_admin_deployer = User("Admin\nDeployer")
        n_id_github_oauth = Github("GitHub\nOAuth")

    with Cluster(
        "Azure Subscription noalz | rg-hacker-board-prod (centralus)",
        graph_attr={**cluster_style, "bgcolor": "#E3F2FD"},
    ) as clu_sub_prod:
        with Cluster("Edge + Auth", graph_attr={**cluster_style, "bgcolor": "#E8F5E9"}) as clu_tier_edge:
            n_id_entra_auth = ActiveDirectory("Microsoft\nEntra ID")

        with Cluster("Compute Tier", graph_attr={**cluster_style, "bgcolor": "#E1F5FE"}) as clu_tier_compute:
            n_app_acr_registry = ContainerRegistries("crhackerboardprod\nACR Basic")
            n_app_plan_b1 = AppServicePlans("asp-hacker-board-prod\nB1 Linux")
            n_web_site_container = AppServices("app-hacker-board-prod\nExpress + SPA")
            n_id_app_mi = EntraManagedIdentities("System MI\nDefaultAzureCredential")

        with Cluster("Data Tier", graph_attr={**cluster_style, "bgcolor": "#FFF3E0"}) as clu_tier_data:
            n_data_cosmos_main = CosmosDb("cosmos-hacker-board-prod\nNoSQL Serverless")

        with Cluster("Observability", graph_attr={**cluster_style, "bgcolor": "#F3E5F5"}) as clu_tier_ops:
            n_ops_appi_main = ApplicationInsights("appi-hacker-board-prod")
            n_ops_law_main = LogAnalyticsWorkspaces("law-hacker-board-prod")

    n_edge_users_participants >> edge_runtime("request") >> n_web_site_container
    n_web_site_container >> edge_runtime("request") >> n_data_cosmos_main
    n_app_acr_registry >> edge_runtime("request") >> n_web_site_container

    n_edge_users_participants >> edge_control("auth") >> n_id_github_oauth
    n_id_github_oauth >> edge_control("auth") >> n_web_site_container
    n_edge_admin_deployer >> edge_control("admin") >> n_id_entra_auth
    n_id_entra_auth >> edge_control("auth") >> n_web_site_container
    n_web_site_container >> edge_control("admin") >> n_id_app_mi
    n_id_app_mi >> edge_control("read/write") >> n_data_cosmos_main
    n_app_plan_b1 >> edge_control("admin") >> n_web_site_container

    n_web_site_container >> edge_observability("telemetry") >> n_ops_appi_main
    n_data_cosmos_main >> edge_observability("telemetry") >> n_ops_law_main
    n_ops_appi_main >> edge_observability("telemetry") >> n_ops_law_main

print(f"Diagram generated: {OUT_FILE}.png")
