"""
HackerBoard — Deployment Dependency Diagram
> Generated by design agent | 2026-02-21

Generate:
  python3 agent-output/hacker-board/04-dependency-diagram.py
"""

import os

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import ContainerRegistries
from diagrams.azure.database import CosmosDb
from diagrams.azure.general import ResourceGroups
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces
from diagrams.azure.network import DNSPrivateZones, PrivateEndpoint, VirtualNetworks
from diagrams.azure.web import AppServices, AppServicePlans

OUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "04-dependency-diagram")

graph_attr = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.9",
    "ranksep": "1.0",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "15",
    "dpi": "150",
}

node_attr = {
    "fontname": "Arial Bold",
    "fontsize": "11",
    "labelloc": "t",
}

cluster_style = {
    "margin": "30",
    "fontname": "Arial Bold",
    "fontsize": "13",
}


def edge_runtime(flow_label: str):
    return Edge(style="bold", color="#2E7D32", label=flow_label)


def edge_control(flow_label: str):
    return Edge(style="dashed", color="#1565C0", label=flow_label)


def edge_observability(flow_label: str):
    return Edge(style="dotted", color="#7B1FA2", label=flow_label)


with Diagram(
    "HackerBoard — Deployment Dependencies\n(App Service + ACR + VNet + Cosmos DB PE)",
    filename=OUT_FILE,
    show=False,
    direction="LR",
    graph_attr=graph_attr,
    node_attr=node_attr,
):
    with Cluster("Azure Subscription noalz", graph_attr={**cluster_style, "bgcolor": "#E3F2FD"}) as clu_sub_root:
        with Cluster("rg-hacker-board-prod", graph_attr={**cluster_style, "bgcolor": "#E1F5FE"}) as clu_rg_core:
            n_ops_rg_main = ResourceGroups("rg-hacker-board-prod")

            with Cluster("Foundation", graph_attr={**cluster_style, "bgcolor": "#F3E5F5"}) as clu_tier_foundation:
                n_ops_law_main = LogAnalyticsWorkspaces("law-hacker-board-prod")
                n_ops_appi_main = ApplicationInsights("appi-hacker-board-prod")

            with Cluster("Data", graph_attr={**cluster_style, "bgcolor": "#FFF3E0"}) as clu_tier_data:
                n_data_cosmos_main = CosmosDb("cosmos-hacker-board-prod")

            with Cluster("Networking", graph_attr={**cluster_style, "bgcolor": "#E0F2F1"}) as clu_tier_network:
                n_net_vnet = VirtualNetworks("vnet-hacker-board-prod")
                n_net_pe = PrivateEndpoint("pep-cosmos-hacker-board-prod")
                n_net_dns = DNSPrivateZones("privatelink.\ndocuments.azure.com")

            with Cluster("Compute", graph_attr={**cluster_style, "bgcolor": "#E8F5E9"}) as clu_tier_compute:
                n_app_acr_registry = ContainerRegistries("crhackerboardprod")
                n_web_plan_b1 = AppServicePlans("asp-hacker-board-prod")
                n_web_app_main = AppServices("app-hacker-board-prod")

    n_ops_rg_main >> edge_control("admin") >> n_ops_law_main
    n_ops_rg_main >> edge_control("admin") >> n_data_cosmos_main
    n_ops_rg_main >> edge_control("admin") >> n_net_vnet
    n_ops_rg_main >> edge_control("admin") >> n_app_acr_registry
    n_ops_rg_main >> edge_control("admin") >> n_web_plan_b1

    n_ops_law_main >> edge_observability("telemetry") >> n_ops_appi_main

    # Networking dependencies
    n_net_vnet >> edge_control("subnet") >> n_net_pe
    n_net_vnet >> edge_control("dns link") >> n_net_dns
    n_data_cosmos_main >> edge_control("private link") >> n_net_pe
    n_net_pe >> edge_control("dns group") >> n_net_dns

    # Compute dependencies
    n_web_plan_b1 >> edge_control("admin") >> n_web_app_main
    n_app_acr_registry >> edge_runtime("image pull") >> n_web_app_main
    n_net_vnet >> edge_control("vnet integration") >> n_web_app_main
    n_data_cosmos_main >> edge_runtime("read/write\n(via PE)") >> n_web_app_main
    n_ops_appi_main >> edge_observability("telemetry") >> n_web_app_main

print(f"Diagram generated: {OUT_FILE}.png")
