"""
HackerBoard — Runtime Flow Diagram
> Generated by design agent | 2026-02-20

Generate:
  python3 agent-output/hacker-board/04-runtime-diagram.py
"""

import os

from diagrams import Cluster, Diagram, Edge
from diagrams.azure.compute import ContainerRegistries
from diagrams.azure.database import CosmosDb
from diagrams.azure.identity import ActiveDirectory, EntraManagedIdentities
from diagrams.azure.monitor import ApplicationInsights, LogAnalyticsWorkspaces
from diagrams.azure.web import AppServices
from diagrams.onprem.client import Users
from diagrams.onprem.vcs import Github

OUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "04-runtime-diagram")

graph_attr = {
    "bgcolor": "white",
    "pad": "0.8",
    "nodesep": "0.9",
    "ranksep": "1.1",
    "splines": "spline",
    "fontname": "Arial Bold",
    "fontsize": "15",
    "dpi": "150",
}

node_attr = {
    "fontname": "Arial Bold",
    "fontsize": "11",
    "labelloc": "t",
}

cluster_style = {
    "margin": "30",
    "fontname": "Arial Bold",
    "fontsize": "13",
}


def edge_runtime(flow_label: str):
    return Edge(style="bold", color="#2E7D32", label=flow_label)


def edge_control(flow_label: str):
    return Edge(style="dashed", color="#1565C0", label=flow_label)


def edge_observability(flow_label: str):
    return Edge(style="dotted", color="#7B1FA2", label=flow_label)


with Diagram(
    "HackerBoard — Runtime Flow\n(App Service Easy Auth + Express + Cosmos DB)",
    filename=OUT_FILE,
    show=False,
    direction="LR",
    graph_attr=graph_attr,
    node_attr=node_attr,
):
    with Cluster("External", graph_attr={**cluster_style, "bgcolor": "#F5F5F5"}) as clu_ext_surface:
        n_edge_users_participants = Users("Hackathon\nParticipants")
        n_id_github_oauth = Github("GitHub\nOAuth")

    with Cluster(
        "Azure Subscription noalz | rg-hacker-board-prod",
        graph_attr={**cluster_style, "bgcolor": "#E3F2FD"},
    ) as clu_sub_platform:
        with Cluster("Edge + Identity", graph_attr={**cluster_style, "bgcolor": "#E8F5E9"}) as clu_tier_identity:
            n_id_entra_auth = ActiveDirectory("Microsoft\nEntra ID")

        with Cluster("Compute", graph_attr={**cluster_style, "bgcolor": "#E1F5FE"}) as clu_tier_compute:
            n_web_app_main = AppServices("app-hacker-board-prod\nExpress server")
            n_app_api_routes = AppServices("/api/* handlers\n(13 routes)")
            n_id_app_mi = EntraManagedIdentities("System MI\nDefaultAzureCredential")
            n_app_acr_registry = ContainerRegistries("crhackerboardprod\nACR Basic")

        with Cluster("Data", graph_attr={**cluster_style, "bgcolor": "#FFF3E0"}) as clu_tier_data:
            n_data_cosmos_main = CosmosDb("cosmos-hacker-board-prod\nServerless")

        with Cluster("Observability", graph_attr={**cluster_style, "bgcolor": "#F3E5F5"}) as clu_tier_observability:
            n_ops_appi_main = ApplicationInsights("appi-hacker-board-prod")
            n_ops_law_main = LogAnalyticsWorkspaces("law-hacker-board-prod")

    n_edge_users_participants >> edge_runtime("request") >> n_web_app_main
    n_web_app_main >> edge_runtime("request") >> n_app_api_routes
    n_app_api_routes >> edge_runtime("read/write") >> n_data_cosmos_main
    n_app_acr_registry >> edge_runtime("request") >> n_web_app_main

    n_edge_users_participants >> edge_control("auth") >> n_id_github_oauth
    n_id_github_oauth >> edge_control("auth") >> n_web_app_main
    n_id_entra_auth >> edge_control("auth") >> n_web_app_main
    n_app_api_routes >> edge_control("admin") >> n_id_app_mi

    n_web_app_main >> edge_observability("telemetry") >> n_ops_appi_main
    n_app_api_routes >> edge_observability("telemetry") >> n_ops_appi_main
    n_data_cosmos_main >> edge_observability("telemetry") >> n_ops_law_main
    n_ops_appi_main >> edge_observability("telemetry") >> n_ops_law_main

print(f"Diagram generated: {OUT_FILE}.png")
